// 앱에 기본으로 들어가는 콘텐츠 (버킷리스트 · 밸런스 게임 · 취향 설문)

export const BUCKET_CATEGORIES = ["일상", "데이트", "여행", "도전", "기념", "미래"] as const;

export const DEFAULT_BUCKET: { title: string; emoji: string; category: (typeof BUCKET_CATEGORIES)[number] }[] = [
  { title: "커플 사진 찍기", emoji: "📸", category: "일상" },
  { title: "같은 옷 맞춰 입고 나가기", emoji: "👕", category: "일상" },
  { title: "서로 머리 말려주기", emoji: "💇", category: "일상" },
  { title: "같이 장 보고 요리하기", emoji: "🍳", category: "일상" },
  { title: "하루 종일 집에서 영화 몰아보기", emoji: "🎬", category: "일상" },
  { title: "손편지 주고받기", emoji: "💌", category: "일상" },
  { title: "서로 화장·꾸며주기", emoji: "💄", category: "일상" },
  { title: "같이 운동하기", emoji: "🏃", category: "일상" },
  { title: "새벽까지 수다 떨기", emoji: "🌙", category: "일상" },
  { title: "서로의 최애 음식 만들어주기", emoji: "🍝", category: "일상" },

  { title: "놀이공원 가기", emoji: "🎢", category: "데이트" },
  { title: "한강에서 치맥", emoji: "🍗", category: "데이트" },
  { title: "전시회 가기", emoji: "🖼️", category: "데이트" },
  { title: "방탈출 성공하기", emoji: "🔐", category: "데이트" },
  { title: "보드게임 카페 가기", emoji: "🎲", category: "데이트" },
  { title: "코인노래방에서 듀엣", emoji: "🎤", category: "데이트" },
  { title: "인생네컷 10장 모으기", emoji: "🎞️", category: "데이트" },
  { title: "공방에서 커플템 만들기", emoji: "💍", category: "데이트" },
  { title: "야구장 직관", emoji: "⚾", category: "데이트" },
  { title: "피크닉 가기", emoji: "🧺", category: "데이트" },
  { title: "자전거 타기", emoji: "🚲", category: "데이트" },
  { title: "벚꽃 구경", emoji: "🌸", category: "데이트" },
  { title: "단풍 구경", emoji: "🍁", category: "데이트" },
  { title: "첫눈 같이 맞기", emoji: "❄️", category: "데이트" },
  { title: "불꽃축제 보기", emoji: "🎆", category: "데이트" },
  { title: "아쿠아리움 가기", emoji: "🐠", category: "데이트" },
  { title: "오락실에서 인형 뽑기", emoji: "🧸", category: "데이트" },
  { title: "심야 영화 보기", emoji: "🍿", category: "데이트" },

  { title: "바다 보러 가기", emoji: "🌊", category: "여행" },
  { title: "1박 2일 여행", emoji: "🧳", category: "여행" },
  { title: "기차 타고 즉흥 여행", emoji: "🚆", category: "여행" },
  { title: "제주도 가기", emoji: "🍊", category: "여행" },
  { title: "해외여행 가기", emoji: "✈️", category: "여행" },
  { title: "캠핑하기", emoji: "⛺", category: "여행" },
  { title: "일출 보기", emoji: "🌅", category: "여행" },
  { title: "별 보러 가기", emoji: "✨", category: "여행" },
  { title: "온천 가기", emoji: "♨️", category: "여행" },
  { title: "서로 고향 구경시켜주기", emoji: "🏡", category: "여행" },

  { title: "등산해서 정상 찍기", emoji: "⛰️", category: "도전" },
  { title: "같이 새로운 취미 배우기", emoji: "🎨", category: "도전" },
  { title: "커플 댄스 챌린지", emoji: "💃", category: "도전" },
  { title: "하루 휴대폰 없이 데이트", emoji: "📵", category: "도전" },
  { title: "얼굴에 낙서하고 사진 찍기", emoji: "🖍️", category: "도전" },
  { title: "번지점프나 짚라인", emoji: "🪂", category: "도전" },
  { title: "같이 봉사활동 하기", emoji: "🤝", category: "도전" },
  { title: "서로 모르는 음식 도전하기", emoji: "🌶️", category: "도전" },

  { title: "100일 기념 데이트", emoji: "💯", category: "기념" },
  { title: "커플 링 맞추기", emoji: "💍", category: "기념" },
  { title: "깜짝 이벤트 해주기", emoji: "🎁", category: "기념" },
  { title: "1주년 여행", emoji: "🥂", category: "기념" },
  { title: "서로 생일상 차려주기", emoji: "🎂", category: "기념" },
  { title: "타임캡슐 묻기", emoji: "⏳", category: "기념" },
  { title: "우리만의 노래 정하기", emoji: "🎵", category: "기념" },

  { title: "서로 가족에게 인사하기", emoji: "👨‍👩‍👧", category: "미래" },
  { title: "같이 반려식물 키우기", emoji: "🪴", category: "미래" },
  { title: "커플 통장 만들기", emoji: "🐷", category: "미래" },
  { title: "10년 뒤 편지 쓰기", emoji: "📮", category: "미래" },
  { title: "우리 집 인테리어 상상해보기", emoji: "🛋️", category: "미래" },
  { title: "평생 함께하기", emoji: "💞", category: "미래" },
];

export type BalanceQuestion = { id: string; a: string; b: string };

export const BALANCE: BalanceQuestion[] = [
  { id: "b01", a: "연락 매일 100통", b: "하루 1통이지만 진심 가득" },
  { id: "b02", a: "깻잎 떼어주기 OK", b: "깻잎 절대 NO" },
  { id: "b03", a: "데이트는 계획파", b: "데이트는 즉흥파" },
  { id: "b04", a: "싸우면 바로 풀기", b: "하루 생각하고 풀기" },
  { id: "b05", a: "평생 여름만", b: "평생 겨울만" },
  { id: "b06", a: "집 데이트", b: "밖 데이트" },
  { id: "b07", a: "깜짝 선물", b: "갖고 싶은 거 같이 고르기" },
  { id: "b08", a: "애인의 이성 친구 1명", b: "애인의 전 애인과 친구" },
  { id: "b09", a: "매일 짧게 만나기", b: "일주일에 한 번 하루 종일" },
  { id: "b10", a: "산 여행", b: "바다 여행" },
  { id: "b11", a: "애칭으로 부르기", b: "이름으로 부르기" },
  { id: "b12", a: "아침형 커플", b: "올빼미형 커플" },
  { id: "b13", a: "기념일 크게 챙기기", b: "평소에 자주 챙기기" },
  { id: "b14", a: "내 폰 다 보여주기", b: "서로 폰은 프라이버시" },
  { id: "b15", a: "맛집 웨이팅 1시간", b: "근처 아무 데나 바로" },
  { id: "b16", a: "커플룩 완전 똑같이", b: "은근히 깔맞춤만" },
  { id: "b17", a: "공포 영화", b: "로맨스 영화" },
  { id: "b18", a: "데이트 비용 반반", b: "번갈아 가며 내기" },
  { id: "b19", a: "SNS에 커플 사진 자랑", b: "우리끼리만 간직" },
  { id: "b20", a: "애인이 요리 잘함", b: "애인이 청소 잘함" },
  { id: "b21", a: "같이 늦잠", b: "같이 일찍 일어나 산책" },
  { id: "b22", a: "치킨", b: "피자" },
  { id: "b23", a: "애인이 나보다 키 큼", b: "애인이 나보다 힘 셈" },
  { id: "b24", a: "말로 하는 사랑 표현", b: "행동으로 하는 사랑 표현" },
  { id: "b25", a: "여행 숙소는 호텔", b: "여행 숙소는 감성 숙소" },
  { id: "b26", a: "애인 친구들과 자주 어울리기", b: "둘이서만 오붓하게" },
  { id: "b27", a: "평생 떡볶이 금지", b: "평생 라면 금지" },
  { id: "b28", a: "서운한 건 바로 말하기", b: "쌓였다가 한 번에" },
  { id: "b29", a: "고양이 키우기", b: "강아지 키우기" },
  { id: "b30", a: "10년 뒤 미래 보기", b: "처음 만난 날로 돌아가기" },
];

export type SurveyQuestion = { id: string; category: string; q: string; options: string[] };

export const SURVEY_CATEGORIES = ["음식", "데이트", "여행", "생활", "연애"] as const;

export const SURVEY: SurveyQuestion[] = [
  { id: "s01", category: "음식", q: "제일 좋아하는 음식 종류는?", options: ["한식", "양식", "일식", "중식", "분식"] },
  { id: "s02", category: "음식", q: "매운 거 어디까지 먹어?", options: ["신라면도 매워", "불닭까진 OK", "매울수록 좋아"] },
  { id: "s03", category: "음식", q: "민트초코는?", options: ["최고야", "치약 맛…", "있으면 먹음"] },
  { id: "s04", category: "음식", q: "탕수육은?", options: ["부먹", "찍먹", "아무거나"] },
  { id: "s05", category: "음식", q: "야식 하나만 고르면?", options: ["치킨", "라면", "떡볶이", "족발·보쌈"] },
  { id: "s06", category: "데이트", q: "이상적인 데이트 시간대는?", options: ["아침 일찍", "점심부터", "저녁부터 밤까지"] },
  { id: "s07", category: "데이트", q: "데이트 코스 정하는 건?", options: ["내가 짤래", "네가 짜줘", "같이 정하자"] },
  { id: "s08", category: "데이트", q: "비 오는 날 데이트는?", options: ["집콕 최고", "카페 투어", "비 맞으며 산책도 좋아"] },
  { id: "s09", category: "데이트", q: "기념일 선물로 받고 싶은 건?", options: ["편지", "꽃", "갖고 싶던 물건", "같이 하는 경험"] },
  { id: "s10", category: "여행", q: "여행 스타일은?", options: ["빡빡하게 다 보기", "여유롭게 쉬기", "반반"] },
  { id: "s11", category: "여행", q: "가고 싶은 여행지는?", options: ["국내 바다", "국내 산·숲", "가까운 해외", "먼 해외"] },
  { id: "s12", category: "여행", q: "여행 짐은?", options: ["최소한으로", "혹시 몰라 다 챙김"] },
  { id: "s13", category: "생활", q: "주말 아침 기상 시간은?", options: ["8시 전", "10시쯤", "점심 넘어서"] },
  { id: "s14", category: "생활", q: "에어컨 온도는?", options: ["18도 꽁꽁", "24도 적당히", "선풍기면 충분"] },
  { id: "s15", category: "생활", q: "스트레스 풀 때는?", options: ["먹기", "자기", "운동", "수다"] },
  { id: "s16", category: "생활", q: "나는 어떤 사람?", options: ["집순·집돌이", "밖순·밖돌이", "그때그때"] },
  { id: "s17", category: "연애", q: "내 사랑의 언어는?", options: ["다정한 말", "스킨십", "선물", "함께하는 시간", "챙겨주는 행동"] },
  { id: "s18", category: "연애", q: "연락 스타일은?", options: ["틈틈이 자주", "중요한 것만", "전화가 좋아"] },
  { id: "s19", category: "연애", q: "싸웠을 때 나는?", options: ["바로 대화", "혼자 정리할 시간 필요", "먼저 장난치며 풂"] },
  { id: "s20", category: "연애", q: "애칭은?", options: ["자기야", "이름", "우리만의 별명"] },
];

export const PASTELS = ["bg-blush", "bg-lilac", "bg-peach", "bg-mint", "bg-sky", "bg-lemon"] as const;
